# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  vltest:
    name: VL Test
    runs-on: docker-24
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.27

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Build VL Test
        run: go build -ldflags="-s -w" -o vltest .

      - name: Run tests
        run: go test -v ./...

      - name: Validate formatting
        run: go fmt ./...

      - name: Upload binary artifact
        uses: forgejo/upload-artifact@v5
        with:
          name: vltest
          path: vltest

  vltest-lint:
    name: VL Test Lint
    runs-on: docker-24
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version: 1.27

      - name: GolangCI Lint
        uses: https://github.com/golangci/golangci-lint-action@v9
        with:
          version: latest
